### ISSUE TITLE
Provide datetimes directly from ArchiveEvent and ArchiveData objects

### ISSUE THREAD

**Issue by willrogers** [willrogers/aapy#36]
The retrieved data objects return timestamps, but requests are done in terms of UTC datetimes. Two people are converting the timestamps back into datetimes immediately.

Proposal:

    class ArchiveEvent(object):
        ...
        @property
        def datetime(self):
            return utils.utc_datetime(self._timestamp)

and:

    class ArchiveData(object):
        ....
        @property
        def datetimes(self):
            # could be better vectorised?
            return numpy.array(utils.utc_datetime(ts) for ts in self._timestamps)

**Comment by mfurseman** [comment]
Looks good.

When implementing a similar function in MachineStatus I checked to see if numpy provided vectorised routines for arbitrary functions, the consensus seems to be there was not, so what reads most Pythonic is likely to be 'best'.

**Comment by willrogers** [comment]
I ended up with:

`ArchiveEvent`:

        def datetime(self, tz=UTC):
            """return a datetime using the specified timezone"""

`ArchiveData`:

        def datetimes(self, tz=UTC):
            """return a numpy array of datetimes using the specified timezone"""

**Comment by willrogers** [comment]
Released in version 0-3.
