### ISSUE TITLE
Inconsistent API

### ISSUE THREAD

**Issue by mfurseman** [willrogers/aapy#44]
I can access the properties on an ArchiveData object,
`data.values`,
`data.pv`,
however the datetimes method has no property flag and require a function call,
`data.datetimes()`.
[](url)
Is this the intention or is there a missing  [`@property`](https://github.com/willrogers/aapy/blob/master/aa/data.py#L98)?

**Comment by willrogers** [comment]
I agree it seems a bit inconsistent, but it is intentional because I want to be able to pass a timezone as an argument, defaulting to UTC.

https://stackoverflow.com/questions/5715620/python-how-to-pass-more-than-one-argument-to-the-property-getter

**Comment by willrogers** [comment]
How about `data.datetimes()` and `data.utc_datetimes`?

**Comment by mfurseman** [comment]
utc_datetimes seems appropriate. Callers would then explicitly acknowledge the datetime format they are expecting.

**Comment by willrogers** [comment]
In that case, I probably shouldn't give a default to the `data.datetimes()` and `event.datetime()` method.

**Comment by willrogers** [comment]
These methods are now available.
